apiVersion: v1
kind: Service
metadata:
  name: thumbnail-generator-api
  labels:
    app.kubernetes.io/name: thumbnail-generator-api
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: thumbnail-generator-api
