apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  labels:
    app.kubernetes.io/name: thumbnail-generator-s3
type: Opaque
data:
  rootUser: {{ .Values.s3.env.username | b64enc | quote }}
  rootPassword: {{ .Values.s3.env.username | b64enc | quote }}