{{- if .Values.task.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: thumbnail-generator-task
  labels:
    app.kubernetes.io/name: thumbnail-generator-task
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thumbnail-generator-task
  minReplicas: {{ .Values.task.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.task.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.task.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.task.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.task.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.task.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
